### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by supperthomas** [supperthomas/Dockerfiles#8]
- [ ] nuttx
- [ ] zephyr
- [ ] btstack

**Comment by supperthomas** [comment]
- [ ]  Mynewt
- [ ] NIMBLE
- [ ] mbedos
- [ ] [RIOT](https://github.com/RIOT-OS/RIOT)
- [ ] [Contiki](https://github.com/contiki-os/contiki)
- [ ] [threadx](https://github.com/azure-rtos/threadx)

**Comment by supperthomas** [comment]
- [ ] [micropython](https://github.com/micropython/micropython)

**Comment by supperthomas** [comment]
- [ ] alios things
- [ ] tencent os
- [ ] harmoey
- [ ] tinyos

**Comment by supperthomas** [comment]
ESP -IDF
ESP-ADF
